# Blog
keywords: XiaMoHuaHuo_CN,XM,XMCN,HuaHuo_CN,夏沫花火
author: XiaMoHuaHuo_CN
sidebar_title: 夏沫花火のBLOG
description: Keep doing,Keep loving.
avatar: https://fs.lolimapis.ml/QQUserAvatar/?qc=2549619802
logo:
  url: https://media.xmnetwork.ga/api?path=/blog/avatar.jpg&raw=true
  title: 'Here is my Blog!'
icon: /images/favicon.png

# Social Accounts
barlink:
  twitter: XiaMoHuaHuo_CN
  weibo: 
  github: XiaMoHuaHuo-CN
  afdian: HuaHuo-CN

# Comment
duoshuo: 
disqus: 
gentie: 
# Waline comments https://waline.js.org
waline:
  enable: true
  serverurl: https://comment.xmnetwork.ga
  placeholder: 说点什么......
