# Blog
keywords: XiaMoHuaHuo_CN,XM,XMCN,HuaHuo_CN,夏沫花火
author: XiaMoHuaHuo_CN
description: Keep doing,Keep loving.
avatar: https://fs.lolimapis.ml/QQUserAvatar/?qc=2549619802

# Social Accounts
twitter: HuaHuo_CN
rss: 
weibo: 
instagram: 
github: XiaMoHuaHuo-CN
facebook: 

# Comment
duoshuo: 
disqus: 
gentie: 
# Valine comments https://valine.js.org
valine:
  enable: true # if you want use valine, please set enable: true
  appid: zrC2pgksyDeBk5vt6nBaeF0S-MdYXbMMI
  appkey: e2sifj5sJfquOUS60xEaHkfM
  qurlid: zrc2pgks
  notify: false # true/false:mail notify !!!Test,Caution. https://github.com/xCss/Valine/wiki/Valine-%E8%AF%84%E8%AE%BA%E7%B3%BB%E7%BB%9F%E4%B8%AD%E7%9A%84%E9%82%AE%E4%BB%B6%E6%8F%90%E9%86%92%E8%AE%BE%E7%BD%AE
  verify: false # true/false:verify code
  avatar: mm # avatar style https://github.com/xCss/Valine/wiki/avatar-setting-for-valine
  placeholder: 说点什么...... # comment box placeholder

